spring:
  application:
    name: AnonymousMessenger
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 200ms
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: qwerty
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

rabbitmq:
  queues:
    first:
      name: incoming_messages
      routing-key: message.incoming.routing.key
      queue_delay:
        name: delay_queue
    second:
      name: outcoming_messages
      routing-key: message.outgoing.routing.key
      queue_delay:
        name: delay_queue
    status:
      name: message_statues
      routing-key: message.status.routing.key
      queue_delay:
        name: delay_queue

  exchange:
    name: message_exchange

database:
  count:
    last-messages: 20